import mongoose, { Schema, Document } from 'mongoose';

export interface IProject extends Document {
  promoteur: mongoose.Types.ObjectId;
  
  // Basic Info
  title: string;
  slug: string;
  description: string;
  shortDescription?: string; // courte description du projet (max 150 caractères)
  projectOverview?: string; // aperçu détaillé du projet
  locationDescription?: string; // description de la localisation
  progressDescription?: string; // description de l'état d'avancement
  projectType: 'villa' | 'immeuble';
  availability?: string; // disponibilité du projet

  typeDetails?: {
    villa?: {
      landArea?: number;
      builtArea?: number;
      units?: number;
      bedrooms?: number;
    };
    immeuble?: {
      floors?: number;
      totalUnits?: number;
      elevators?: number;
      parkingSpaces?: number;
    };
  };
  
  // Location
  country: string;
  city: string;
  area: string;
  address?: string;
  coordinates?: {
    lat: number;
    lng: number;
  };
  
  // Project Details
  typologies: Array<{
    name: string; // e.g., "F3", "F4"
    surface: number; // in m²
    price: number;
    available: number;
  }>;
  
  priceFrom: number;
  currency: string;
  
  // Timeline
  timeline: {
    preCommercializationDate?: Date;
    constructionStartDate?: Date;
    deliveryDate?: Date;
    actualDeliveryDate?: Date;
  };
  
  // Status
  status: 'pre-commercialisation' | 'en-construction' | 'gros-oeuvre' | 'livre' | 'pause' | 'archive' | 'suspended';
  publicationStatus: 'draft' | 'pending' | 'published' | 'rejected';
  
  pauseInfo?: {
    reason: 'intemperies' | 'administratif' | 'financement' | 'autre';
    description: string;
    pausedAt: Date;
    estimatedResumeDate?: Date;
    supportingDocuments?: string[];
  };
  
  // Media
  media: {
    coverImage?: string;
    renderings: Array<string | { url: string; mimeType?: string; sizeBytes?: number; uploadedAt?: Date }>;
    photos: Array<string | { url: string; mimeType?: string; sizeBytes?: number; uploadedAt?: Date }>;
    videos: Array<string | { url: string; mimeType?: string; sizeBytes?: number; uploadedAt?: Date }>;
    floorPlans: Array<string | { url: string; mimeType?: string; sizeBytes?: number; uploadedAt?: Date }>;
  };
  
  // Features & Amenities
  features: string[];
  amenities: string[];
  
  // Updates and changes log
  lastUpdateDate?: Date;
  updateFrequency: number; // days since last update
  totalUpdates: number;
  
  changesLog: Array<{
    field: string;
    oldValue: any;
    newValue: any;
    reason: string;
    changedBy: mongoose.Types.ObjectId;
    changedAt: Date;
  }>;
  
  // Delays & Risks
  delays: Array<{
    reason: string;
    originalDate: Date;
    newDate: Date;
    mitigationPlan: string;
    reportedAt: Date;
  }>;
  
  risks: Array<{
    type: 'financement' | 'approvisionnement' | 'administratif' | 'autre';
    description: string;
    severity: 'low' | 'medium' | 'high';
    mitigationPlan: string;
    status: 'active' | 'resolved';
    reportedAt: Date;
    resolvedAt?: Date;
  }>;
  
  // Trust & Quality
  trustScore: number; // 0-100
  completenessScore: number; // 0-100
  
  // Team assigned to project
  assignedTeam: Array<{
    userId: mongoose.Types.ObjectId;
    role: 'commercial' | 'technique';
  }>;
  
  // Stats
  views: number;
  favorites: number;
  totalLeads: number;
  conversionRate: number;
  
  // FAQ
  faq: Array<{
    question: string;
    answer: string;
    addedAt: Date;
  }>;
  
  // Admin moderation
  moderationNotes: Array<{
    note: string;
    addedBy: mongoose.Types.ObjectId;
    addedAt: Date;
  }>;
  
  rejectionReason?: string;
  
  // Featured/Promoted
  isFeatured: boolean;
  featuredUntil?: Date;
  
  // Active boosts
  boosts?: Array<{
    paymentId: mongoose.Types.ObjectId; // Reference to Payment record
    type: 'basic' | 'premium' | 'enterprise' | 'custom';
    startDate: Date;
    endDate: Date;
    status: 'active' | 'expired' | 'canceled';
  }>;
  
  // Timestamps (auto-generated by mongoose)
  createdAt: Date;
  updatedAt: Date;
}

const ProjectSchema: Schema = new Schema({
  promoteur: { type: Schema.Types.ObjectId, ref: 'Promoteur', required: true, index: true },
  
  title: { type: String, required: true, trim: true },
  slug: { type: String, required: true, unique: true, lowercase: true },
  description: { type: String, required: true },
  shortDescription: { type: String, maxlength: 150 },
  projectOverview: { type: String },
  locationDescription: { type: String },
  progressDescription: { type: String },
  projectType: { type: String, enum: ['villa', 'immeuble'], required: true },
  availability: { type: String },

  typeDetails: {
    villa: {
      landArea: { type: Number },
      builtArea: { type: Number },
      units: { type: Number },
      bedrooms: { type: Number },
    },
    immeuble: {
      floors: { type: Number },
      totalUnits: { type: Number },
      elevators: { type: Number },
      parkingSpaces: { type: Number },
    },
  },
  
  country: { type: String, required: true, index: true },
  city: { type: String, required: true, index: true },
  area: { type: String, required: true },
  address: { type: String },
  coordinates: {
    lat: { type: Number },
    lng: { type: Number },
  },
  
  typologies: [{
    name: { type: String, required: true },
    surface: { type: Number, required: true },
    price: { type: Number, required: true },
    available: { type: Number, required: true },
  }],
  
  priceFrom: { type: Number, required: true, index: true },
  currency: { type: String, default: 'EUR' },
  
  timeline: {
    preCommercializationDate: { type: Date },
    constructionStartDate: { type: Date },
    deliveryDate: { type: Date, index: true },
    actualDeliveryDate: { type: Date },
  },
  
  status: { 
    type: String, 
    enum: ['pre-commercialisation', 'en-construction', 'gros-oeuvre', 'livre', 'pause', 'archive', 'suspended'],
    default: 'pre-commercialisation',
    index: true
  },
  publicationStatus: { 
    type: String, 
    enum: ['draft', 'pending', 'published', 'rejected'],
    default: 'draft',
    index: true
  },
  
  pauseInfo: {
    reason: { type: String, enum: ['intemperies', 'administratif', 'financement', 'autre'] },
    description: { type: String },
    pausedAt: { type: Date },
    estimatedResumeDate: { type: Date },
    supportingDocuments: [{ type: String }],
  },
  
  media: {
    coverImage: { type: String },
    renderings: [{ type: Schema.Types.Mixed }],
    photos: [{ type: Schema.Types.Mixed }],
    videos: [{ type: Schema.Types.Mixed }],
    floorPlans: [{ type: Schema.Types.Mixed }],
  },
  
  features: [{ type: String }],
  amenities: [{ type: String }],
  
  lastUpdateDate: { type: Date },
  updateFrequency: { type: Number, default: 0 },
  totalUpdates: { type: Number, default: 0 },
  
  changesLog: [{
    field: { type: String, required: true },
    oldValue: { type: Schema.Types.Mixed },
    newValue: { type: Schema.Types.Mixed },
    reason: { type: String, required: true },
    changedBy: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    changedAt: { type: Date, default: Date.now },
  }],
  
  delays: [{
    reason: { type: String, required: true },
    originalDate: { type: Date, required: true },
    newDate: { type: Date, required: true },
    mitigationPlan: { type: String, required: true },
    reportedAt: { type: Date, default: Date.now },
  }],
  
  risks: [{
    type: { 
      type: String, 
      enum: ['financement', 'approvisionnement', 'administratif', 'autre'],
      required: true 
    },
    description: { type: String, required: true },
    severity: { type: String, enum: ['low', 'medium', 'high'], required: true },
    mitigationPlan: { type: String, required: true },
    status: { type: String, enum: ['active', 'resolved'], default: 'active' },
    reportedAt: { type: Date, default: Date.now },
    resolvedAt: { type: Date },
  }],
  
  trustScore: { type: Number, default: 0, min: 0, max: 100 },
  completenessScore: { type: Number, default: 0, min: 0, max: 100 },
  
  assignedTeam: [{
    userId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    role: { type: String, enum: ['commercial', 'technique'], required: true },
  }],
  
  views: { type: Number, default: 0 },
  favorites: { type: Number, default: 0 },
  totalLeads: { type: Number, default: 0 },
  conversionRate: { type: Number, default: 0 },
  
  faq: [{
    question: { type: String, required: true },
    answer: { type: String, required: true },
    addedAt: { type: Date, default: Date.now },
  }],
  
  moderationNotes: [{
    note: { type: String, required: true },
    addedBy: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    addedAt: { type: Date, default: Date.now },
  }],
  
  rejectionReason: { type: String },
  
  isFeatured: { type: Boolean, default: false },
  featuredUntil: { type: Date },

  boosts: [{
    paymentId: { type: Schema.Types.ObjectId, ref: 'Payment', required: true },
    type: { 
      type: String, 
      enum: ['basic', 'premium', 'enterprise', 'custom'],
      required: true 
    },
    startDate: { type: Date, required: true },
    endDate: { type: Date, required: true },
    status: { 
      type: String, 
      enum: ['active', 'expired', 'canceled'],
      default: 'active'
    }
  }],
}, { timestamps: true });

ProjectSchema.index({ promoteur: 1, status: 1 });
ProjectSchema.index({ publicationStatus: 1, status: 1 });
ProjectSchema.index({ trustScore: -1 });
ProjectSchema.index({ 'timeline.deliveryDate': 1 });
ProjectSchema.index({ slug: 1 });
ProjectSchema.index({ country: 1, city: 1, projectType: 1 });

export default mongoose.model<IProject>('Project', ProjectSchema);
